version: 2
jobs:
  build:
    docker: 
      - image: node:8
    working_directory: /home/ubuntu/COMS20805-SentimentAnalysis
    steps:
      - checkout
      - run: mkdir -p /home/COMS20805-SentimentAnalysis/artifacts
      - run: cd frontend && npm install
      - run: cd frontend && npm test
      - store_artifacts:
          path: /home/ubuntu/COMS20805-SentimentAnalysis/artifacts